### ISSUE TITLE
CSS for some ANDable filters is a little odd

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#12]
See screenshot: words are overflowing the text box: 
![image](https://user-images.githubusercontent.com/9271438/45353376-909fd480-b5b2-11e8-9d91-6fb3237afe6e.png)

present in FF and Chrome

**Comment by AdrianBZG** [comment]
@yochannah Thanks for spotting that one, looks like I had some bad CSS there, you can check now: http://im-browser-prototype.herokuapp.com/

**Comment by yochannah** [comment]
fixed!
