### ISSUE TITLE
API modal - close button is too close to the save button. 

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#13]
![image](https://user-images.githubusercontent.com/9271438/45354346-36ecd980-b5b5-11e8-9633-f2f35b4e44bd.png)

Could we move close over to the left of the modal so it doesn't get clicked accidentally and/or as an x at the top right of the modal? 🦄

**Comment by AdrianBZG** [comment]
@yochannah Should be good now 👍

**Comment by yochannah** [comment]
so fast! 💨
