### ISSUE TITLE
inform user of a bad api key

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#14]
If I paste a bad API key into the API key modal, the save as list button disappears from the imtable, which is great. Is the API key used (yet) in any other place in the app?

What might be even better is if we tell the user the API key isn't any good. e.g. something like 

>Error: API key provided for HumanMine is not a valid API key - please check you have entered it correctly.

**Comment by AdrianBZG** [comment]
@yochannah Is there a REST point to given a API key, check if its valid? Maybe I could use that to check it when the user clicks "Save" to prevent to use a invalid one.

**Comment by yochannah** [comment]
www.flymine.org/query/service/user/whoami?token=sometoken should either give you details about the user or tell you it's a bad key.

**Comment by yochannah** [comment]
Nice one! Tested ok.
