### ISSUE TITLE
Usability: add textual description to the API key and "Change views" buttons

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#16]
Very few icons have automatically clear meaning to users, so it is usually best to add a text description as well as the icon itself. You can read more about icon usability on the neilsen norman group blog: https://www.nngroup.com/articles/icon-usability/ 

![image](https://user-images.githubusercontent.com/9271438/51381525-46080900-1b0c-11e9-95fb-ac6328fd9bcb.png)

**Comment by AdrianBZG** [comment]
@yochannah Do you mean like adding a tooltip, e.g.:

![image](https://user-images.githubusercontent.com/8275330/51384131-abafc180-1b1b-11e9-8ed2-dd03fb500b2c.png)

?

(Is it showing for you?)

**Comment by AdrianBZG** [comment]
Yes, that sounds better!

**Comment by AdrianBZG** [comment]
@yochannah Added :smile:

**Comment by yochannah** [comment]
![image](https://user-images.githubusercontent.com/9271438/51385432-304c1100-1b17-11e9-80ff-c5a0230fd08d.png)
 could we add a space between the icons and the the text? We might also want to differentiate between active views and the two toolbar icons on the right...

**Comment by AdrianBZG** [comment]
Done!
