### ISSUE TITLE
Graphs for custom views

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#17]
If I add a pathway view along the top, the graph displayer box is present but empty. 

![image](https://user-images.githubusercontent.com/9271438/51381725-d5152100-1b0c-11e9-93c7-9814506ce8a2.png)

**Comment by AdrianBZG** [comment]
@yochannah There's definitely something wrong, as one of the JSON files is missing (new filters config, currently I only see the old one), let me figure out where it has gone on holidays :/

**Comment by AdrianBZG** [comment]
@yochannah Added the config and made a pull request. About the empty box:

In the case of Pathway, it doesn't have an Organism facet right below it, as Gene or Protein do, and this is needed for the left plot. What about checking if facet for one graphic exists before showing it, and only show those graphics that are available for that view. In case of 0, show a "No available graphics for this view" message on the box?

**Comment by yochannah** [comment]
sounds good! Let's also shrink the box so it doesn't take up a bunch of vertical space in this case.

**Comment by AdrianBZG** [comment]
Sure :+1:

**Comment by AdrianBZG** [comment]
Done
