### ISSUE TITLE
Usability - make it clearer how you select a specific gene or list

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#18]
It's not entirely obvious to a new user how to filter by single gene (or other entity) or gene lists. From Gos:

>I added an API key for my humanMine account but I couldn't see how to find my personal
list, nor search for specific gene etc.

I'll admit it took me a few seconds to figure it out as well. Any ideas on how we could make it more obvious?

**Comment by AdrianBZG** [comment]
@yochannah What about a new button to display the user's personal list (in case it has added a key for current mine)?

For how to search by single entity or list, maybe it's a good idea to add a "How To" button, that explains some use cases like this one?

**Comment by yochannah** [comment]
sounds like it's worth a shot! This way users won't have to guess list
names so it would be much easier to use - nice!

**Comment by LakshSingla** [comment]
@AdrianBZG @yochannah Is this issue addressed by my recent PR #31. Or something else needs to done ? :thinking:

**Comment by AdrianBZG** [comment]
@LakshSingla Yes, looks like it is! :trophy:
