### ISSUE TITLE
Phenotypes (HPO/MPO) filter

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/InterMine-Data-Browser-Tool#21]
It would be interesting to add a new sidebar filter, to filter by phenotypes. This would be very interesting to be able to analyze only those genes/proteins where the human had some specific characteristics, such as nocturia or abnormality of body height.

The idea is to have an autocomplete input box, in the same line as, for instance, the pathways filter, making it easier for the user to search for a specific phenotype. This filter should allow multiple terms at the same time, something that the pathways filter already supports.

The concrete facet of interest is "HPO.Term". An example XML query showing all phenotypes available in HumanMine is:

```
<query model="genomic" view="HPOTerm.identifier HPOTerm.name HPOTerm.ontology.name HPOTerm.description" sortOrder="HPOTerm.identifier ASC" >
</query>
```

This is a good first issue for prospective GSoC students, as it allows to get acquainted with handling constraints on intermine-tables.

**Comment by LakshSingla** [comment]
@AdrianBZG I would like to take this issue up. Unfortunately, I am unable to get familiarized with the terms pertaining to Biology, causing confusion at times due to lack of logical structure of what is happening :disappointed: . Is there any concise text I can refer to so that I am able to understand the terminologies (an overview) ? Alternatively, you can give me a list of keywords (required to take up this issue) which I can look up :smiley:

**Comment by yochannah** [comment]
@LakshSingla here's an example of imjs queries - does it help at all? 

https://jsbin.com/vacefe/edit?html,console - I'd also suggest looking at our query builder tutorial: https://flymine.readthedocs.io/en/latest/query-builder/Documentationquerybuilder.html and using the generate code feature of intermine to build a query - 

![image](https://user-images.githubusercontent.com/9271438/51839568-78321b80-2301-11e9-8d45-d498a9693c9a.png)

the pic above is the same result in yeastmine as the code in the jsbin.

**Comment by LakshSingla** [comment]
@yochannah Thanks for the help :smile: Things are much clearer to me now

**Comment by LakshSingla** [comment]
@AdrianBZG One more query :sweat_smile: I checked `request-handler.js` which requests data from the local server but doesnot do anything about it. Can you please help me know where is the incoming query processed (when the webpage is first loaded).

**Comment by LakshSingla** [comment]
I started working on creating the backend endpoint for HPOTerm but the following error is arising
![screenshot from 2019-01-30 04-06-41](https://user-images.githubusercontent.com/30999375/51945393-a8ce9e00-2444-11e9-8b07-03a398a4eb3d.png)

I think I may have queried the XML wrongly but it doesn't seem so from the XML generated in HumanMine's query builder. Can you please point out what maybe the error in this case :disappointed:

**Comment by LakshSingla** [comment]
@AdrianBZG I have added a PR for the issue and most of the work is done except adding the constraint to the table, which does not seem to be working under the name "phenotypeName" or "HPOTerm". I am unable to find the docs of `im-table`. Can you please help me out with this issue ...
Further more, we need a thumbicon (as with other filters) to display to the left. I am currently using pathways icon.

**Comment by AdrianBZG** [comment]
Hi @LakshSingla , indeed, the hpoTerm.name attribute is found when you go to Gene > Diseases in the Query Builder, here is an example JS code that display the Gene summary together with the associated hpoTerm.name:

```
var imtables = require('imtables');

var selector = '#some-elem';
var service  = {root: 'http://www.humanmine.org/humanmine/service/'};
var query    = {
  "from": "Gene",
  "select": [
    "symbol",
    "name",
    "primaryIdentifier",
    "secondaryIdentifier",
    "organism.name",
    "diseases.hpoAnnotations.hpoTerm.name"
  ],
  "orderBy": [
    {
      "path": "symbol",
      "direction": "ASC"
    }
  ]
};

imtables.loadTable(
  selector, // Can also be an element, or a jQuery object.
  {"start":0,"size":25}, // May be null
  {service: service, query: query} // May be an imjs.Query
).then(
  function (table) { console.log('Table loaded', table); },
  function (error) { console.error('Could not load table', error); }
);
```

Hope it helps.

**Comment by LakshSingla** [comment]
@AdrianBZG Moved the discussion to the PR itself :smiley: Thanks for the help.

**Comment by AdrianBZG** [comment]
Closed
