### ISSUE TITLE
Top-right button to show lists and filter by them

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/InterMine-Data-Browser-Tool#27]
It is interesting to add a button on the top-right of the browser, just beside the "Add view" and "Add API key" ones, where a user can click and get the list of the lists it has stored in it's account.

This should check that the user has actually added a valid API key for the current mine in the "Add API key" section. This is stored as a LocalStorage object, so it should be easy to check if the key exists.

Then, add a button on the side of each list name, that says "Select", that just adds the constraint of showing that list genes in the im-table.

**Comment by LakshSingla** [comment]
@AdrianBZG I would like to work on this issue :) Lemme read up the Docs about API keys and get back to you.

**Comment by AdrianBZG** [comment]
@LakshSingla This is going to be useful: https://intermine.readthedocs.io/en/1.8.5/web-services/how-do-i/

Specifically, look at this block of code to get the personal user lists:

`var util      = require('util');
var intermine = require('imjs');

var flymine = new intermine.Service({
  root: 'www.flymine.org/query',
  token: null // supply a token to see your own lists.
});

flymine.fetchLists().done(function(lists) {
  lists.forEach(function(list) {
    console.log(util.format("%s: ( %d %ss )", list.name, list.size, list.type));
  });
});`

**Comment by LakshSingla** [comment]
This may seem like a stupid question, but where do I get my API Key after logging in (I logged in via Google Account). I am unable to find it :sweat_smile:

**Comment by AdrianBZG** [comment]
@LakshSingla After logging in e.g. HumanMine, go to http://www.humanmine.org/humanmine/mymine.do?subtab=account, then press "Generate a new API key" at the bottom of the page, and the key will appear 😄

**Comment by LakshSingla** [comment]
So I began working on it. I have created a back end route which queries it and integrated it with the front end (currently I am logging it only). I have a few questions :
 - Does the local storage obect `api-keys` have only apiKeys and nulls or should I put extra guards to check if it is a valid key ? (I saw in the codebase that you already have placed some checks while storing the key in the codebase, are anymore required ?)
 - What should I do with the returned object ? There are around 147 lists created by default. How should the UI look. Is everything to be displayed ?
Here's the logged screenshot :- 
![screenshot from 2019-02-09 23-33-54](https://user-images.githubusercontent.com/30999375/52524457-3458f200-2cc3-11e9-93a7-e3ce8394b46d.png)

 - How to add constraints on the `im-tables` involving lists, are there any docs present ?

**Comment by AdrianBZG** [comment]
@LakshSingla The API keys in the JSON object should already be valid, as the code is doing a check. We should show the 147 lists for the moment, so let's make that window horizontally scrollable.

To constraint with a list is just the "IN" operator. Here is an example to constraint the table with the list "PL_GenomicsEngland_GenePanel:Genetic_Epilepsy_Syndromes":

```
var imtables = require('imtables');

var selector = '#some-elem';
var service  = {root: 'http://www.humanmine.org/humanmine/service/'};
var query    = {
  "from": "Gene",
  "select": [
    "symbol",
    "name",
    "primaryIdentifier",
    "secondaryIdentifier",
    "length",
    "organism.name"
  ],
  "where": [
    {
      "path": "Gene",
      "op": "IN",
      "value": "PL_GenomicsEngland_GenePanel:Genetic_Epilepsy_Syndromes",
      "code": "A"
    }
  ]
};

imtables.loadTable(
  selector, // Can also be an element, or a jQuery object.
  {"start":0,"size":25}, // May be null
  {service: service, query: query} // May be an imjs.Query
).then(
  function (table) { console.log('Table loaded', table); },
  function (error) { console.error('Could not load table', error); }
);
```

You can see more examples by clicking a list from http://www.humanmine.org/humanmine/bag.do?subtab=view and then generating the JavaScript query from the table :smile:

**Comment by LakshSingla** [comment]
@AdrianBZG Are the names of the list unique, i.e. can I use them as an identifier? I would need to save the lists applied in an array, so that I can highlight the corresponding element in the modal later. From the  query which you mentioned above, it seems as if the name of the list is its unique identifier. Also, is it necessary to send one's api key with the above query ?? (so that one can fetch personal lists also)

**Comment by AdrianBZG** [comment]
@LakshSingla Yes, they are unique. So we want both public lists and private lists. This means that if the user hasnt specified a key, it will only see public lists. If it has, then it will see public and private ones.

**Comment by LakshSingla** [comment]
- I wanted to ask how would intermine distinguish between me and any other person, if we both have saved a list with same name.
 - Also, is it possible for me to have more than 1 list as a constraint, or only 1 list at a time ?

I am uploading the screenshot of UI I have designed so far. Also, I am thinking of adding a filter box so as to traverse lists quickly by their name :smile: Suggestions and opinions welcome ?
![screenshot from 2019-02-10 22-33-55](https://user-images.githubusercontent.com/30999375/52536732-7eee7300-2d84-11e9-90f5-0c3c88a19a05.png)

**Comment by AdrianBZG** [comment]
@LakshSingla So for personal lists there is no problem of same names as other user, because they are personal, so you're only able to see your lists, or the lists of one specified API key.

To have more than one list in the constraint, please refer to my answer in your PR :smile: 

Exactly, the path could be Gene, Protein or X, where X is any view chosen by the user. So the "from" parameter of the query should be the currentView text value.
