### ISSUE TITLE
Add select to the Views manager for adding a new view

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/InterMine-Data-Browser-Tool#28]
Currently, in order to add a new custom view to the browser, it needs to write it in the corresponding input field in the Views manager:

![image](https://user-images.githubusercontent.com/8275330/51759125-cbb92500-20c7-11e9-9145-ae8016f76e69.png)

This leads to a problem, which is that the user may write a view (class/facet) that actually doesn't exist in the current mine. On this extent, the idea is to change this input field by a select one, that gets populated with the available views (classes/facets) in the current mine. This auto-filled select feature is already available, for instance, in the GO Annotation filter:

![image](https://user-images.githubusercontent.com/8275330/51759245-1044c080-20c8-11e9-87b2-1c57d48d884f.png)

So the idea is to replicate and adapt accordingly this code.

This issue directly closes this one and #23

**Comment by suryatejreddy** [comment]
Hey, I would like to work on this issue. I understood the problem. I am currently going through the code.

**Comment by AdrianBZG** [comment]
Hi @suryatejreddy ,

If you take a look at https://github.com/intermine/InterMine-Data-Browser-Tool/blob/master/src/js/main-view.js#L155, you can see that using the model?format=json path from the mine API, I get the classes with the tag im:preferredBagType to build the default view buttons.

The idea is to use this route to get all the classes, not only the im:preferredBagType ones, and use that array of names to feed the Select.

Hope it helps.

**Comment by AdrianBZG** [comment]
Closed :+1:
