### ISSUE TITLE
CORS problems

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/InterMine-Data-Browser-Tool#33]
CORS error when changing to TargetMine:

![image](https://user-images.githubusercontent.com/8275330/54287471-9c8a4480-459d-11e9-9dce-4bea6bd4b13b.png)

**Comment by AdrianBZG** [comment]
Currently we avoid showing HTTPS mines in the mine dropdown, but maybe we can do better.

**Comment by Zemotacqy** [comment]
Hey, the same issue persists in the data-browser tool currently deployed. The CORS issue must be handled server side, in that case, the only solution I am guessing would be to allow CORS at server side in the respective request URLs. I would like to take up this issue. Do let me know if you have something else in mind.

**Comment by lazycipher** [comment]
@Zemotacqy, Any Updates?

**Comment by Zemotacqy** [comment]
> @Zemotacqy, Any Updates?

Replied on discord.

**Comment by AdrianBZG** [comment]
No longer an issue after porting to imjs (#72).
