### ISSUE TITLE
mine dropdown - clicking on the arrow doesn't work

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#35]
Clicking on the arrow on the left of the dropdown doesn't do anything on FF or Chrome - you have to click on the word "humanmine" to get a response 

![image](https://user-images.githubusercontent.com/9271438/54288376-461e0580-459f-11e9-83d7-da38d16a2c03.png)

**Comment by AdrianBZG** [comment]
True, I've never realized that!

**Comment by VarunBhandia** [comment]
Hi, @AdrianBZG @yochannah I have fixed the issue. Please review my PR.

**Comment by VarunBhandia** [comment]
I have only changed the form-control width from 200px to 180px.
![Screenshot from 2019-03-20 10-06-54](https://user-images.githubusercontent.com/27995669/54659513-21bead80-4af8-11e9-8b7e-5c00c225b218.png)

**Comment by AdrianBZG** [comment]
Well done @VarunBhandia !

Closed by d1edf34
