### ISSUE TITLE
Add preferredOrganisms optional array to mineConfigs

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/InterMine-Data-Browser-Tool#36]
Add preferredOrganisms optional array to mineConfigs. Load them first always in the pie chart and in the left side organism filter

**Comment by VarunBhandia** [comment]
I am working on this issue. @AdrianBZG just want to confirm we want to load pie chart before the rendering of the table or any other component right?

**Comment by AdrianBZG** [comment]
Done
