### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by dmahajan980** [intermine/InterMine-Data-Browser-Tool#53]
It seems that the dependencies have not been updated for a long time and it may be better if we stick to the latest versions. For the record, I've attached the screenshot of the dependencies which can be updated.
![upd](https://user-images.githubusercontent.com/37256767/72409117-e1b56f00-378a-11ea-9297-87d4e495df20.png)

**Comment by AdrianBZG** [comment]
Hi @dmahajan980 ,

Thanks for spotting that, it looks that dependencies are quite old now 😟 , would you like to pick up this issue?

**Comment by AdrianBZG** [comment]
PS: Some of the dependencies have been now updated by https://github.com/intermine/InterMine-Data-Browser-Tool/pull/52, but some others might still be outdated.

**Comment by dmahajan980** [comment]
I think, I could update the dependencies one by one while going through the code base. So @AdrianBZG please assign it to me.

**Comment by dmahajan980** [comment]
@AdrianBZG I am getting a lot of errors while running the project locally.
![err1](https://user-images.githubusercontent.com/37256767/72445525-d5a3ce80-37d7-11ea-94a7-3c156904f3b4.png)
![err2](https://user-images.githubusercontent.com/37256767/72445531-da688280-37d7-11ea-8e17-78025ab4fb7c.png)
I'm not sure about it but do you think that the above could possibly be due to some error in #52?
