### ISSUE TITLE
Buttons on the navigation bar overlap in some devices

### ISSUE THREAD

**Issue by dmahajan980** [intermine/InterMine-Data-Browser-Tool#55]
The screenshots attached below itself explain the issue.

![Nav](https://user-images.githubusercontent.com/37256767/72994690-94d23800-3e1d-11ea-91de-a6552ce9a619.png)
![nav2](https://user-images.githubusercontent.com/37256767/72995038-3bb6d400-3e1e-11ea-825e-9780a36536c5.png)

This is because the navigation bar is not completely responsive.

**Comment by AdrianBZG** [comment]
Hi @dmahajan980 ,

Would you like to try and make it responsive? That would be pretty nice 😄

**Comment by dmahajan980** [comment]
Sure @AdrianBZG ! I will make a PR soon to fix this.

**Comment by AdrianBZG** [comment]
Related to a bigger task: #64

**Comment by AdrianBZG** [comment]
Fixed by ada6fc9

**Comment by dmahajan980** [comment]
@AdrianBZG I think you referenced the wrong commit while closing this. The one you mentioned was about Updating Dependencies. I think this is the correct one: 728da45
