### ISSUE TITLE
Footer text moves out of the box in some devices

### ISSUE THREAD

**Issue by dmahajan980** [intermine/InterMine-Data-Browser-Tool#56]
The text in the footer moves out of the container on some of the defined screen sizes. Here's the screenshot for the issue:

![Footer](https://user-images.githubusercontent.com/37256767/73006359-880b0f80-3e30-11ea-82bc-5b5860941212.png)

**Comment by AdrianBZG** [comment]
Related to #64

**Comment by AdrianBZG** [comment]
Fixed by ada6fc9

**Comment by dmahajan980** [comment]
@AdrianBZG I think you referenced the wrong commit while closing this. The one you mentioned was about Updating Dependencies. I think this is the correct one: 728da45
