### ISSUE TITLE
Improve Getting Started or BUILD.md

### ISSUE THREAD

**Issue by dmahajan980** [intermine/InterMine-Data-Browser-Tool#63]
More details to the Building docs can be added for better documentation. We can change the BUILD.md to getting-started.md containing more detailed instructions on setting up the repository, running it locally on the machine and other related information about processes and workflows.

**Comment by AdrianBZG** [comment]
Thanks for the suggestion, that should be helpful 😄

**Comment by dmahajan980** [comment]
@AdrianBZG I have made some changes and will soon send a pull request for it.
