### ISSUE TITLE
Unwanted grey color background and extra row in the header

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/InterMine-Data-Browser-Tool#65]
There's an unwanted space with grey background above the header, and there is a grey background under the menu.

Ideally we would like to remove that unwanted header spacing and use the same bbackground color (white?) everywhere.

Screenshot:

![image](https://user-images.githubusercontent.com/8275330/74449489-87d0c380-4e74-11ea-88ee-fe8636e58d3c.png)

**Comment by AdrianBZG** [comment]
Fixed by ada6fc9

**Comment by dmahajan980** [comment]
@AdrianBZG I think you referenced the wrong commit while closing this. The one you mentioned was about _Updating Dependencies_. I think this is the correct one: 728da45d044e821429c63c60fa69f27334826e6e
