### ISSUE TITLE
Server Started message on console

### ISSUE THREAD

**Issue by lazycipher** [intermine/InterMine-Data-Browser-Tool#66]
As of now, when we run `npm start`, we don't get any console message saying that the server is started already and that's why one keeps waiting on that step.
Adding an alert message `Server Started at Port: XYZ` at the end of all bundling processes will look good.

I'm working on this.

**Comment by AdrianBZG** [comment]
Thanks.

Specifying the actual URL where you can access the browser sounds better than just the port. Something like http://IP:PORT/

**Comment by lazycipher** [comment]
I guess we should close this issue as the PR is merged now which solves this.
