### ISSUE TITLE
dev server of browser tool

### ISSUE THREAD

**Issue by lazycipher** [intermine/InterMine-Data-Browser-Tool#67]
Currently, the `npm run dev` command in project executes the command `gulp && webpack --config webpack.config.js`. We're missing webpack dependency in package.json and the config file `webpack.config.js` as well.

**Comment by lazycipher** [comment]
Hi @AdrianBZG,
Can you explain to me a bit about the plan with webpack?

**Comment by AdrianBZG** [comment]
@lazycipher The idea to have hot reloading when running 'dev' version, so that changes in the CSS style, JavaScript, etc, are compiled real-time and you can see the changes without having to close and open the app again.

Does that make sense?

**Comment by AdrianBZG** [comment]
Or maybe we can use something different instead of webpack?

**Comment by lazycipher** [comment]
I got the idea! I'll look around for alternatives if available and proceed with webpack if it's best(which I think it is).

**Comment by AdrianBZG** [comment]
Hi @lazycipher , any updates on this? 😄

**Comment by lazycipher** [comment]
Hi @AdrianBZG,
I've exams going on! As soon it gets over, I'll get back to it.

**Comment by JM-Mendez** [comment]
Hi @AdrianBZG, requesting to be assigned this task. Once assigned, do you have a preference for either webpack or gulp?

**Comment by AdrianBZG** [comment]
Hi @JM-Mendez , I don't have a preference, really. I leave that up to you to choose the one most suitable for the current codebase 😄

**Comment by AdrianBZG** [comment]
Closed by @JM-Mendez on PR#76
