### ISSUE TITLE
Update screenshots in the readme to reflect latest version (1.2) look

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/InterMine-Data-Browser-Tool#74]
Update screenshots in the README.md to reflect latest version (1.2) look

**Comment by PrastutiUpadhaya** [comment]
Hi, can I try this out?

**Comment by AdrianBZG** [comment]
Hi @PrastutiUpadhaya,

Sure! 👍

**Comment by PrastutiUpadhaya** [comment]
> Hi @PrastutiUpadhaya,
> 
> Sure! 👍

Thanks @AdrianBZG !

**Comment by rafayhasankhan** [comment]
Hi there, @AdrianBZG would you assign this issue to me.

**Comment by PrastutiUpadhaya** [comment]
Hi @AdrianBZG I have created a pull request for this, can you please see and suggest changes, if any?

**Comment by PrastutiUpadhaya** [comment]
Also, I have downloaded the release of version 1.2, and have another folder named InterMine-Data-Browser-Tool-1.2, and I cd into it, however it shows error whenever I do npm test or npm start in this folder. The version I have updated screenshots with is the one I got from the cloned repo, which I believe is 1.1.0

**Comment by nehasangeetajha** [comment]
hi @AdrianBZG , if this issue is not resolved can u please assign this to me?
