### ISSUE TITLE
Class filters along top - allow additional filters

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#8]
Right now we have Gene and Protein across the top of the tool. Theoretically we might wish to browse classes other than Gene and Protein. 

This will need to be done defensively similar to the left-side filters - i.e. check the model and don't add filters for classes that don't exist. In this case it should be slightly easier, though as all classes will be root-level entities in the model.

So, suggested implementation: 

- [x] Show any classes tagged `preferredBagType` (see [example](https://gist.github.com/yochannah/a4f9c6a8a502d3daaf418c7d8ec51be7#file-humanminemodel-json-L1361)) along the top bar (as we currently do with gene and protein)
- [x] Add model to allow the user to add/remove any other class as a view type (store this in localstorage so the user doesn't have to re-add every time they revisit).

**Comment by AdrianBZG** [comment]
@yochannah Is there a way to get the classes like your example (https://gist.github.com/yochannah/a4f9c6a8a502d3daaf418c7d8ec51be7#file-humanminemodel-json-L1361) from the HumanMine API? I've tried parsing the XML from http://www.humanmine.org/humanmine/service/model without luck

**Comment by yochannah** [comment]
yup! http://www.humanmine.org/humanmine/service/model?format=json

http://iodocs.apps.intermine.org/ can be handy to find out API things like this :)

**Comment by AdrianBZG** [comment]
@yochannah The first point is done: "Show any classes tagged preferredBagType (see example) along the top bar (as we currently do with gene and protein)". Going to tackle the second one this week.

**Comment by AdrianBZG** [comment]
Working!
