### ISSUE TITLE
Background-color for  button not visible enough in the menu bar.

### ISSUE THREAD

**Issue by uimarshall** [intermine/InterMine-Data-Browser-Tool#85]
## Description
The background-color for the button containing `protein` text is not visible enough in the menu bar.
It needs to be given a background that is visible for good contrast in line with other items in the menu bar.

**Comment by uimarshall** [comment]
@Nikhil-Vats, I have checked the ``navbar.pug`` file but the `div` that contains the button is not displaying contents. I could only see `div#headerButtons`.
Can you help with the file where I can fix the button?

**Comment by ahlamatout** [comment]
Can I work on this issue?

**Comment by Emuohwo** [comment]
I'm an outreachy applicant. I would like to work on this issue

**Comment by uimarshall** [comment]
> I'm an outreachy applicant. I would like to work on this issue

@Emuohwo, you can look at the webpage and look for areas of improvement, then create an issue. I am currently working on this issue.

**Comment by salmabadawy7** [comment]
I'm an outreachy applicant. I would like to work on this issue

**Comment by muskangupta-iitr** [comment]
@AdrianBZG @Nikhil-Vats  For this issue, we can use bootstrap outline buttons for creating contrast and to easily identify the selected one.

![bar](https://user-images.githubusercontent.com/50856599/77120481-f51cd900-6a5e-11ea-8bd0-977affd5620c.png)
