### ISSUE TITLE
The checkboxes are showing over the Names in the Dataset name part

### ISSUE THREAD

**Issue by shaymaa91** [intermine/InterMine-Data-Browser-Tool#88]
@Nikhil-Vats, In the Dataset name part when you try to choose a dataSet, the checkbox is showing over the name of the datasets and it should be showing before or or after the dataset name.
here is a screenshot showing the problem:
![image](https://user-images.githubusercontent.com/61957173/76765344-4ac75c00-67a7-11ea-98bb-c57bfb6a73b6.png)

**Comment by AdrianBZG** [comment]
This is probably largely solved by addressing #64 , which intends to port the app to React, so we would prefer to do that instead of addressing each responsiveness-related issue individually.

Thanks.
