### ISSUE TITLE
Add "current class" filters to left filter bar

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#9]
For now this would simply be adding Gene and Protein filters (dependent on the active tab) to left - probably these will work ok all mines! 

- This will mean we can allow [IN <LISTNAME> queries](http://intermine.readthedocs.io/en/latest/api/pathquery/#list-constraints) if user is [authenticated](https://github.com/AdrianBZG/InterMine-Data-Browser-Tool/issues/69)
- Also allow [LOOKUP query](http://intermine.readthedocs.io/en/latest/api/pathquery/#lookup-constraints) with multiple identifiers pasted in or a single identifier (autocomplete possible here? Maybe not wise?)

This should be dynamic and _not_ hard coded to Gene and Protein classes. I would suggest fixing this after #8 is implemented.

**Comment by yochannah** [comment]
We don't want to remove the buttons on the top. Maybe consider the buttons on the top the view, and the buttons on the left the filters?

**Comment by AdrianBZG** [comment]
@yochannah So if I understand correctly, the idea is to add a new filter that, depending on current view, works e.g. like this:

- If I'm in Proteins view, the user can specify a list in a textbox, and by filtering, the constraint applied is:

{
  select: ["Protein.*"],
  where: [["genes", "IN", "list from the textbox"]]
}

- If in Genes view, it will be:

{
  select: ["Gene.*"],
  where: [["genes", "IN", "list from the textbox"]]
}

Or I'm getting it wrong?

**Comment by yochannah** [comment]
that's exactly it! 

We'd also want the user to be able to type a single identifier and run a LOOKUP query, e.g. type "adh" and show the single gene adh in the view, or type "adh, fkh, bsk" and show all three in the view.

I'm not sure if that should be one input or two - whatever's less confusing. A single smart box with typeahead might be nice?
