### ISSUE TITLE
UI issue - Enhancement for the "Add button", Views manager pop up.

### ISSUE THREAD

**Issue by ahlamatout** [intermine/InterMine-Data-Browser-Tool#91]
Enhancement for the "Add button":
1- Make it the same size as "Close" button on the same pop up.
2- Add some margin above the button to make a space between the button and the item above it.

**Steps to Reproduce**
1- Click on Add view button on the main page.
2- The "Views manager" pop up appears.

**Expected Behaviour**
There should be a space between the "Add" button and the drop-down list above it.

**Actual Behaviour**
No space is between the "Add" button and the drop-down list above it. 

**Settings**

- OS: Windows 10

**Screenshots**
Please see attached.
![Add view - Views manager](https://user-images.githubusercontent.com/62181489/76888907-6147e300-688d-11ea-9a3c-2da6f9967b07.png)

**Comment by ahlamatout** [comment]
Hi @Nikhil-Vats , I opened this issue and I think it's a good first issue.
Can you please assign it to me?

**Comment by salmabadawy7** [comment]
Hi @Nikhil-Vats and @AdrianBZG, I opened this issue and I think it's a good first issue.
Can you please assign it to me?

**Comment by Nikhil-Vats** [comment]
@salmabadawy7 I have assigned this issue to @ahlamatout since she opened it and asked first but you are free to submit a PR as well. Both of your PRs will be counted as contributions in Outreachy. 🎉 😄

**Comment by ahlamatout** [comment]
@Nikhil-Vats Can you please help me in which file should I make the changes? I made some search but with no result.

**Comment by ahlamatout** [comment]
@Nikhil-Vats @AdrianBZG Can you please help me where should I make the changes? in which file? I know what are the changes that should be done, but I can't find the file.
