### ISSUE TITLE
Checkboxes under the "Dataset Name" heading cover text.

### ISSUE THREAD

**Issue by PrastutiUpadhaya** [intermine/InterMine-Data-Browser-Tool#93]
Selecting the Dataset Name option on the toolbar on the left displays various datasets, which have to be checked, however, the checkboxes cover the text.

The checkboxes should ideally be aligned and not cover any text for a neater frontend.

OS: Windows 10

Screenshot
![Screenshot (20)](https://user-images.githubusercontent.com/58902654/77052927-8fdfce00-69f3-11ea-81d8-18c141aec1f3.png)

**Comment by itolimaesther** [comment]
@PrastutiUpadhaya please can I work on this issue?

**Comment by KPoornima** [comment]
Hi! @PrastutiUpadhaya I am interested to work on this issue

**Comment by salmabadawy7** [comment]
hi can i work for this issue

**Comment by Emuohwo** [comment]
I'm interested in this issue. Please assign it to me.

**Comment by guptadiksha307** [comment]
Hi,I'm Diksha, an outreachy applicant. Can I work on this issue please?
